nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'X-API-KEY']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'X-API-KEY']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']